# Generated by Django 6.0 on 2025-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(default='View Artwork', max_length=50)),
                ('button_link', models.CharField(default='/products/', max_length=200)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
